### ISSUE TITLE
Rename repo to "zmon-scheduler"

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-scheduler#6]
I would strongly suggest renaming this repository to "zmon-scheduler" --- the Docker image is now called "zmon-scheduler" too (https://registry.opensource.zalan.do/teams/stups/artifacts/zmon-scheduler/tags). We don't need the "-ng" suffix anymore :smirk:

**Comment by Jan-M** [comment]
Well - rename it then ;)

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Done: https://github.com/zalando/zmon-scheduler
