### ISSUE TITLE
Cleanup of removed entities is not working

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-scheduler#9]
Apparently only the old Python scheduler still does this...

**Comment by hjacobs** [comment]
So "generally" the single entity removal cleanup works. but due to race conditions (e.g. AWS scheduler/worker hasn't pushed results yet), it might not fail sometimes.

We should implement a "brute force" cleanup to eventually remove all stale alerts/check results.

**Comment by Jan-M** [comment]
https://github.com/zalando-zmon/zmon-scheduler/tree/feature-cleanup-alert-change

Finally doing the cleanup after alert definition changes
